easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Stages
        - App\Entity\Formations
        - App\Entity\Entreprises
        - App\Entity\User
